SQLALCHEMY_DATABASE_URI="sqlite:///temp-database.db"
SECRET_KEY="secret key"
JWT_SECRET_KEY="super-secret-jwt-key"
JWT_TOKEN_LOCATION=["cookies"]
JWT_COOKIE_SECURE=True
JWT_COOKIE_SAMESITE="None"
JWT_COOKIE_CSRF_PROTECT=False
JWT_ACCESS_TOKEN_EXPIRES=86400